### ISSUE TITLE
[温馨提示]当前QQ版本过低

### ISSUE THREAD

**Issue by cibimo** [tkkcc/qqimagedeliver#1]
[2022-11-11T19:49:43.585] [ERROR] [Android:xxxx] - [温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面
xxxx system.login.error {
  code: 235,
  message: '[温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面',
  self_id: xxxx
}
login finish
send_msg_interval 10000
send_msg_timeout 10000

**Comment by tkkcc** [comment]
按 https://github.com/takayama-lily/oicq/issues/451#issuecomment-1305906603 修改`/usr/lib/node_modules/qqimagedeliver/node_modules/oicq/lib/core/device.js`

**Comment by cibimo** [comment]
修改后使用qq号+密码的形式仍提示版本过低，因挂在服务器，扫码登录会提示网络环境异常

**Comment by tkkcc** [comment]
修改后我没遇到版本过低

**Comment by 02Alive** [comment]
> 按[takayama-lily/oicq#451（评论）](https://github.com/takayama-lily/oicq/issues/451#issuecomment-1305906603)修改`/usr/lib/node_modules/qqimagedeliver/node_modules/oicq/lib/core/device.js`

按照这个修改改为是网络不稳定，登录失败，怎么改登录设备呀

**Comment by cibimo** [comment]
如果删除device文件确实会出现同样的问题，作为新设备无法登录



| |
zsl6677
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月14日 10:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [tkkcc/qqimagedeliver] [温馨提示]当前QQ版本过低 (Issue #1) |

按takayama-lily/oicq#451（评论）修改/usr/lib/node_modules/qqimagedeliver/node_modules/oicq/lib/core/device.js

按照这个修改改为是网络不稳定，登录失败，怎么改登录设备呀

**Comment by tkkcc** [comment]
先根据[tom-snow](https://github.com/tom-snow)的方法修改`/usr/lib/node_modules/qqimagedeliver/node_modules/oicq/lib/core/device.js`，
然后把账号device.json删了：
```sh
rm -rf /usr/lib/node_modules/qqimagedeliver/QQ号
```
然后命令行里不加密码，通过手机扫码登录。最后加密码登录。

**Comment by cibimo** [comment]
如需服务器登录，可现在本地电脑上安装此项目后扫码登录，将 /usr/local/lib/node_modules/qqimagedeliver/data/<qq号> 内的 device-<qq号>.json 与 token 文件上传至服务器的对应目录，再在服务器使用账号密码登录即可。提示版本过低可尝试运行时添加参数 --platform 2

**Comment by cibimo** [comment]
如需服务器登录，可现在本地电脑上安装此项目后扫码登录，将 /usr/local/lib/node_modules/qqimagedeliver/data/<qq号> 内的 device-<qq号>.json 与 token 文件上传至服务器的对应目录，再在服务器使用账号密码登录即可。提示版本过低可尝试运行时添加参数 --platform 2

**Comment by sjx1995** [comment]
> 如需服务器登录，可现在本地电脑上安装此项目后扫码登录，将 /usr/local/lib/node_modules/qqimagedeliver/data/<qq号> 内的 device-<qq号>.json 与 token 文件上传至服务器的对应目录，再在服务器使用账号密码登录即可。提示版本过低可尝试运行时添加参数 --platform 2

成功解决，谢谢！
